"""
FastAPI application entry point.

This is a minimal setup. Architecture-specific code (routers, middleware, containers)
will be generated by /scaffold after architecture decisions are made in /brainstorm.
"""

from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager

import structlog
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware

from src.settings import settings


logger = structlog.get_logger(__name__)

limiter = Limiter(key_func=lambda: "default", default_limits=["200/minute"])


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:  # noqa: ARG001
    _validate_production_config()
    logger.info("startup", environment=settings.app_env, version=settings.app_version)

    if settings.sentry_dsn:
        import sentry_sdk

        sentry_sdk.init(
            dsn=settings.sentry_dsn,
            environment=settings.app_env,
            traces_sample_rate=0.1,
        )
        logger.info("sentry_initialized")

    yield
    logger.info("shutdown")


def _validate_production_config() -> None:
    """Fail fast if critical production settings are missing or unsafe."""
    if not settings.is_production:
        return
    errors = []
    if settings.debug:
        errors.append("DEBUG must be False in production")
    if not settings.gcs_project_id:
        errors.append("GCS_PROJECT_ID is required in production")
    if not settings.gcs_bucket_name:
        errors.append("GCS_BUCKET_NAME is required in production")
    if errors:
        raise RuntimeError(f"Invalid production configuration: {'; '.join(errors)}")


def create_app() -> FastAPI:
    app = FastAPI(
        title=settings.app_name,
        version=settings.app_version,
        docs_url="/docs" if not settings.is_production else None,
        redoc_url="/redoc" if not settings.is_production else None,
        openapi_url="/openapi.json" if not settings.is_production else None,
        lifespan=lifespan,
    )

    app.state.limiter = limiter

    app.add_middleware(SlowAPIMiddleware)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.allowed_origins,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type", "X-Correlation-ID", "Idempotency-Key"],
        expose_headers=["X-Correlation-ID"],
    )

    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)  # type: ignore[arg-type]

    @app.get(f"{settings.api_prefix}/health")
    async def health_check() -> dict[str, str]:
        return {"status": "ok"}

    return app


app = create_app()
